site_name: Tableplus DB URLs Docs
site_author: tsantor@xstudios.com
# google_analytics: ['UA-ID', '']

copyright: Copyright &copy; 2026 - X Studios™, Inc.

repo_url: https://bitbucket.org/tsantor/tableplus-db-urls/
repo_name: Bitbucket

# Configuration
theme:
  name: 'material'
  palette:
    scheme: default
    primary: custom
    accent: custom
  icon:
    repo: fontawesome/brands/git-alt
  favicon: images/favicon.png
  logo: img/x-logo-white.svg
  font:
    text: Raleway
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top
    # - navigation.footer
    # - navigation.tracking
    # - toc.integrate
    - content.code.copy
    - content.code.annotate

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - sane_lists
  - smarty
  - meta
  # - toc:
  #       toc_depth: 2
  #       permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg # Plugins

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  # - privacy
  # - offline
  - to-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      # author: X Studios Team
      output_path: tableplus-db-urls-documentation.pdf
      cover_title: Tableplus DB URLs
      cover_subtitle: Technical Documentation
      cover_logo: img/xstudios-logo-black.svg
      back_cover: true
      toc_level: 2
      ordered_chapter_level: 3
      # heading_shift: false
      download_link: header
      verbose: false
      debug_html: false

# Customization
extra_css:
  - css/extra.css

# Page tree
nav:
  - Getting Started:
      - index.md

# watch:
#     - docs/css/extra.css
